### ISSUE TITLE
Concurrent test failure

### ISSUE THREAD

**Issue by timcassell** [timcassell/ProtoPromise#107]
https://github.com/timcassell/ProtoPromise/runs/7703914830?check_suite_focus=true

```
ProtoPromiseTests.Threading.PromiseConcurrencyTests.PromiseProgressMayBeSubscribedWhilePromiseIsCompletedAndProgressIsReportedConcurrently_Pending_T(Parallel,Parallel,Parallel,CancelFromToken,Interface,Foreground)
```

```
--IndexOutOfRangeException
   at Proto.Promises.Internal.ValueList`1.get_Item(Int32 index) in D:\a\ProtoPromise\ProtoPromise\ProtoPromise_Unity\Assets\Plugins\ProtoPromise\Core\InternalShared\ValueCollectionsInternal.cs:line 438
   at Proto.Promises.Internal.PromiseRefBase.PromiseMultiAwait`1.InvokeProgressFromContext() in D:\a\ProtoPromise\ProtoPromise\ProtoPromise_Unity\Assets\Plugins\ProtoPromise\Core\Promises\Internal\ProgressInternal.cs:line 814
   at Proto.Promises.Internal.StackUnwindHelper.InvokeProgressors() in D:\a\ProtoPromise\ProtoPromise\ProtoPromise_Unity\Assets\Plugins\ProtoPromise\Core\Promises\Internal\ProgressInternal.cs:line 99
   at Proto.Promises.Internal.PromiseRefBase.DeferredPromiseBase`1.ReportProgressAlreadyIncremented(Fixed32 progress, HandleablePromiseBase progressListener) in D:\a\ProtoPromise\ProtoPromise\ProtoPromise_Unity\Assets\Plugins\ProtoPromise\Core\Promises\Internal\ProgressInternal.cs:line 882
   at Proto.Promises.Internal.PromiseRefBase.DeferredPromiseBase`1.TryReportProgress(Int32 deferredId, Single progress) in D:\a\ProtoPromise\ProtoPromise\ProtoPromise_Unity\Assets\Plugins\ProtoPromise\Core\Promises\Internal\ProgressInternal.cs:line 859
   at Proto.Promises.Internal.DeferredPromiseHelper.TryReportProgress(IDeferredPromise _this, Int32 deferredId, Single progress) in D:\a\ProtoPromise\ProtoPromise\ProtoPromise_Unity\Assets\Plugins\ProtoPromise\Core\Promises\Internal\DeferredInternal.cs:line 48
   at Proto.Promises.Promise`1.Deferred.TryReportProgress(Single progress) in D:\a\ProtoPromise\ProtoPromise\ProtoPromise_Unity\Assets\Plugins\ProtoPromise\Core\Promises\Deferred.cs:line 821
   at ProtoPromiseTests.Threading.PromiseConcurrencyTests.<>c__DisplayClass14_0.<PromiseProgressMayBeSubscribedWhilePromiseIsCompletedAndProgressIsReportedConcurrently_Pending_T>b__3() in D:\a\ProtoPromise\ProtoPromise\ProtoPromise_Unity\Assets\Plugins\ProtoPromiseTests\Tests\Threading\PromiseConcurrencyTests.cs:line 485
   at ProtoPromiseTests.Threading.ThreadHelper.ThreadRunner.Execute() in D:\a\ProtoPromise\ProtoPromise\ProtoPromise_Unity\Assets\Plugins\ProtoPromiseTests\Helpers\ThreadHelper.cs:line 71
```

**Comment by timcassell** [comment]
Reopening since the issue showed up again. https://github.com/timcassell/ProtoPromise/runs/7801237427?check_suite_focus=true
