### ISSUE TITLE
Failed progress test

### ISSUE THREAD

**Issue by timcassell** [timcassell/ProtoPromise#262]
Looks like a deadlock

https://github.com/timcassell/ProtoPromise/actions/runs/6135804448/job/16649930358

```ProtoPromiseTests.Concurrency.PromiseConcurrencyTests.PromiseProgressMayBeSubscribedWhilePromiseIsCompletedAndProgressIsReportedConcurrently_Pending_T(Parallel,InSetup,InSetup,Resolve,Interface,Background)
  Failed PromiseProgressMayBeSubscribedWhilePromiseIsCompletedAndProgressIsReportedConcurrently_Pending_T(Parallel,InSetup,InSetup,Resolve,Interface,Background) [20 s]
  Error Message:
   System.TimeoutException : 10 Action(s) timed out after 00:00:10, there may be a deadlock. Remaining Actions: 1
TearDown : System.TimeoutException : WaitForAllThreadsToComplete timed out after 00:00:10, _runningActionCount: 10
  Stack Trace:
     at ProtoPromiseTests.Concurrency.ThreadHelper.ExecutePendingParallelActions(TimeSpan timeoutPerAction) in /home/runner/work/ProtoPromise/ProtoPromise/Package/Tests/Helpers/ThreadHelper.cs:line 194
   at ProtoPromiseTests.Concurrency.ThreadHelper.ExecuteParallelActions(Int32 repeatCount, Action setup, Action teardown, Action[] actions) in /home/runner/work/ProtoPromise/ProtoPromise/Package/Tests/Helpers/ThreadHelper.cs:line 228
   at ProtoPromiseTests.Concurrency.PromiseConcurrencyTests.PromiseProgressMayBeSubscribedWhilePromiseIsCompletedAndProgressIsReportedConcurrently_Pending_T(ActionPlace subscribePlace, ActionPlace reportPlace, ActionPlace completePlace, CompleteType completeType, ProgressType progressType, SynchronizationType synchronizationType) in /home/runner/work/ProtoPromise/ProtoPromise/Package/Tests/CoreTests/Concurrency/PromiseConcurrencyTests.cs:line 569
--TearDown
   at ProtoPromiseTests.BackgroundSynchronizationContext.WaitForAllThreadsToComplete() in /home/runner/work/ProtoPromise/ProtoPromise/Package/Tests/Helpers/BackgroundSynchronizationContext.cs:line 97
   at ProtoPromiseTests.TestHelper.WaitForAllThreadsToCompleteAndGcCollect() in /home/runner/work/ProtoPromise/ProtoPromise/Package/Tests/Helpers/TestHelper.cs:line 180
   at ProtoPromiseTests.TestHelper.Cleanup() in /home/runner/work/ProtoPromise/ProtoPromise/Package/Tests/Helpers/TestHelper.cs:line 153
   at ProtoPromiseTests.Concurrency.PromiseConcurrencyTests.Teardown() in /home/runner/work/ProtoPromise/ProtoPromise/Package/Tests/CoreTests/Concurrency/PromiseConcurrencyTests.cs:line 32

**Comment by timcassell** [comment]
I ran the test in an infinite loop on my PC for 4 days and was not able to repro. I even reduced my core count down to 2 (to try to more closely match the CI machines), and still nothing.

**Comment by timcassell** [comment]
I'm not sure if it's the same reason, but I keep seeing Unity IL2CPP tests timeout. https://github.com/timcassell/ProtoPromise/actions/runs/6269544696/job/17026131530

**Comment by timcassell** [comment]
The issue is no longer reproducing. It's impossible for me to debug.
